---

- name: ensure kibana service started and enabled
  service:
    name: kibana
    state: started
    enabled: true

- name: restart kibana service
  debug:
    msg: "restart kibana"
  changed_when: true
  when: force_restart | default('no') | bool
  notify:
    - kibana restart
    - kibana status
