---

- name: ensure dependencies are installed
  package:
    name:
      - yum-utils
      - libselinux-python
      - policycoreutils-python

- name: ensure Elastic repository is present
  yum_repository:
    name: "elastic-{{ kibana.version.split('.')[:1] | join('.') }}.x"
    description: "Elastic repository for version {{ kibana.version.split('.')[:1] | join('.') }}.x"
    file: "elastic-{{ kibana.version.split('.')[:1] | join('.') }}.x"
    baseurl: "https://artifacts.elastic.co/packages/{{ kibana.version.split('.')[:1] | join('.') }}.x/yum"
    gpgkey: "http://packages.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: true
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: ensure yum-plugin-versionlock is installed
  package:
    name: yum-plugin-versionlock
  when: kibana.pin_version
